name: merge PR

on:
  pull_request:

jobs:
  merge:
    name: "Merge"
    runs-on: "ubuntu-latest"
    steps:

      - name: "Merge PR (Only by matte-oss)"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.PAT }}"
          script: |
            const creator = context.payload.sender.login
            if (creator !== "matte-oss") {
              console.log("Pull Request is not created by matte-oss, skipping merge.")
              return
            }

            const pull_number = ${{ github.event.pull_request.number }}
            const repository = context.repo

            try {
              await github.rest.pulls.merge({
                merge_method: "merge",
                owner: repository.owner,
                pull_number: pull_number,
                repo: repository.repo,
              })
              console.log("Pull Request merged successfully!")
            } catch (error) {
              console.error("Failed to merge Pull Request:", error)
            }
